packageExtensions:
 "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
 "@chakra-ui/provider@*":
    dependencies:
      "@chakra-ui/portal": "*"
      "@chakra-ui/react-env": "*"
 "@chakra-ui/accordion@*":
    dependencies:
      "framer-motion": "*"
 "@chakra-ui/skeleton@*":
    dependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
 "@chakra-ui/anatomy@*":
    dependencies:
      "@chakra-ui/system": "*"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
